/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Channel as PrismaChannel } from "@prisma/client";

export class ChannelServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.ChannelCountArgs, "select">): Promise<number> {
    return this.prisma.channel.count(args);
  }

  async channels(args: Prisma.ChannelFindManyArgs): Promise<PrismaChannel[]> {
    return this.prisma.channel.findMany(args);
  }
  async channel(
    args: Prisma.ChannelFindUniqueArgs
  ): Promise<PrismaChannel | null> {
    return this.prisma.channel.findUnique(args);
  }
  async createChannel(args: Prisma.ChannelCreateArgs): Promise<PrismaChannel> {
    return this.prisma.channel.create(args);
  }
  async updateChannel(args: Prisma.ChannelUpdateArgs): Promise<PrismaChannel> {
    return this.prisma.channel.update(args);
  }
  async deleteChannel(args: Prisma.ChannelDeleteArgs): Promise<PrismaChannel> {
    return this.prisma.channel.delete(args);
  }
}
